builds:
  - env:
    - CGO_ENABLED=0
archive:
  wrap_in_directory: true
  replacements:
    386: i386
    amd64: x86_64
  files:
    - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
